// ============================================================
//  AI Models Registry  —  central source of truth
//  Fetched at runtime from MODELS_REGISTRY_URL for auto-updates
// ============================================================

export type SpeedRating = "ultrafast" | "fast" | "medium" | "slow";
export type AccuracyRating = "supreme" | "high" | "medium" | "low";
export type OptimizationMode = "token" | "accurate" | "fast" | "aligned";
export type ModelCategory = "text" | "image" | "video" | "tts" | "stt" | "embedding" | "ocr" | "other";

export interface ModelInfo {
  id: string;           // API model id
  name: string;         // Display name
  provider: string;     // Company name
  apiProvider: string;  // Which adapter to use
  contextWindow: number;
  maxOutput: number;
  inputCostPer1M: number;   // USD per 1M input tokens (0 = free/unknown)
  outputCostPer1M: number;
  speed: SpeedRating;
  accuracy: AccuracyRating;
  supportsStreaming: boolean;
  isLatest: boolean;    // Marked true for the newest model in series
  tags: string[];       // e.g. ["reasoning","vision","code"]
  releaseDate: string;  // ISO date
  category?: ModelCategory; // Model type classification
}

// ── Default (bundled) registry ──────────────────────────────
// Overridden by remote fetch if MODELS_REGISTRY_URL is set
export const BUNDLED_MODELS: ModelInfo[] = [
  // ─── OpenAI ────────────────────────────────────────────────
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 128000,
    maxOutput: 16384,
    inputCostPer1M: 2.5,
    outputCostPer1M: 10,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["vision", "code", "reasoning"],
    releaseDate: "2024-05-13",
    category: "text",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 128000,
    maxOutput: 16384,
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    speed: "ultrafast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["fast", "cheap", "code"],
    releaseDate: "2024-07-18",
    category: "text",
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 1048576,
    maxOutput: 32768,
    inputCostPer1M: 2,
    outputCostPer1M: 8,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: true,
    tags: ["vision", "code"],
    releaseDate: "2025-04-14",
    category: "text",
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 1048576,
    maxOutput: 32768,
    inputCostPer1M: 0.4,
    outputCostPer1M: 1.6,
    speed: "ultrafast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["cheap", "fast"],
    releaseDate: "2025-04-14",
    category: "text",
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 1048576,
    maxOutput: 32768,
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    speed: "ultrafast",
    accuracy: "medium",
    supportsStreaming: true,
    isLatest: false,
    tags: ["ultra-cheap", "fast"],
    releaseDate: "2025-04-14",
    category: "text",
  },
  {
    id: "o3",
    name: "o3",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 200000,
    maxOutput: 100000,
    inputCostPer1M: 10,
    outputCostPer1M: 40,
    speed: "slow",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["reasoning", "math", "science"],
    releaseDate: "2025-01-31",
    category: "text",
  },
  {
    id: "o4-mini",
    name: "o4-mini",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 200000,
    maxOutput: 100000,
    inputCostPer1M: 1.1,
    outputCostPer1M: 4.4,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["reasoning", "code", "cheap"],
    releaseDate: "2025-04-16",
    category: "text",
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 200000,
    maxOutput: 100000,
    inputCostPer1M: 10,
    outputCostPer1M: 40,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["reasoning", "code", "vision"],
    releaseDate: "2025-06-01",
    category: "text",
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 200000,
    maxOutput: 100000,
    inputCostPer1M: 10,
    outputCostPer1M: 40,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["reasoning", "code"],
    releaseDate: "2025-11-01",
    category: "text",
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 200000,
    maxOutput: 100000,
    inputCostPer1M: 2,
    outputCostPer1M: 8,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["reasoning", "code"],
    releaseDate: "2025-06-01",
    category: "text",
  },
  {
    id: "o3-pro",
    name: "o3-pro",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 200000,
    maxOutput: 100000,
    inputCostPer1M: 20,
    outputCostPer1M: 80,
    speed: "slow",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["reasoning", "math", "science"],
    releaseDate: "2025-06-10",
    category: "text",
  },
  {
    id: "codex-mini",
    name: "Codex Mini",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 200000,
    maxOutput: 100000,
    inputCostPer1M: 1.5,
    outputCostPer1M: 6,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["code"],
    releaseDate: "2025-05-16",
    category: "text",
  },
  {
    id: "gpt-image-1",
    name: "GPT Image 1",
    provider: "OpenAI",
    apiProvider: "openai",
    contextWindow: 32768,
    maxOutput: 4096,
    inputCostPer1M: 5,
    outputCostPer1M: 40,
    speed: "medium",
    accuracy: "supreme",
    supportsStreaming: false,
    isLatest: true,
    tags: ["image-gen"],
    releaseDate: "2025-04-23",
    category: "image",
  },
  // ─── Anthropic Claude ──────────────────────────────────────
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    provider: "Anthropic",
    apiProvider: "anthropic",
    contextWindow: 200000,
    maxOutput: 16000,
    inputCostPer1M: 15,
    outputCostPer1M: 75,
    speed: "medium",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: true,
    tags: ["reasoning", "writing", "code"],
    releaseDate: "2025-05-01",
    category: "text",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    apiProvider: "anthropic",
    contextWindow: 200000,
    maxOutput: 16000,
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["vision", "code", "writing"],
    releaseDate: "2025-04-01",
    category: "text",
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    provider: "Anthropic",
    apiProvider: "anthropic",
    contextWindow: 200000,
    maxOutput: 16000,
    inputCostPer1M: 15,
    outputCostPer1M: 75,
    speed: "medium",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["reasoning", "writing", "code"],
    releaseDate: "2025-02-24",
    category: "text",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    provider: "Anthropic",
    apiProvider: "anthropic",
    contextWindow: 200000,
    maxOutput: 16000,
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["balanced", "code", "writing"],
    releaseDate: "2025-02-24",
    category: "text",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    apiProvider: "anthropic",
    contextWindow: 200000,
    maxOutput: 8192,
    inputCostPer1M: 1,
    outputCostPer1M: 5,
    speed: "ultrafast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["fast", "cheap"],
    releaseDate: "2025-04-15",
    category: "text",
  },
  {
    id: "claude-3-5-haiku-20241022",
    name: "Claude Haiku 3.5",
    provider: "Anthropic",
    apiProvider: "anthropic",
    contextWindow: 200000,
    maxOutput: 8192,
    inputCostPer1M: 0.8,
    outputCostPer1M: 4,
    speed: "ultrafast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["fast", "cheap"],
    releaseDate: "2024-11-04",
    category: "text",
  },
  // ─── Google Gemini ─────────────────────────────────────────
  {
    id: "gemini-2.5-pro-preview-03-25",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    apiProvider: "google",
    contextWindow: 1000000,
    maxOutput: 65536,
    inputCostPer1M: 1.25,
    outputCostPer1M: 10,
    speed: "medium",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: true,
    tags: ["vision", "reasoning", "long-context"],
    releaseDate: "2025-03-25",
    category: "text",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    apiProvider: "google",
    contextWindow: 1048576,
    maxOutput: 65536,
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["fast", "cheap", "vision"],
    releaseDate: "2025-04-17",
    category: "text",
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    apiProvider: "google",
    contextWindow: 1000000,
    maxOutput: 8192,
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.4,
    speed: "ultrafast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["fast", "cheap", "multimodal"],
    releaseDate: "2025-02-05",
    category: "text",
  },
  // ─── Meta Llama (via Groq) ─────────────────────────────────
  {
    id: "llama-3.3-70b-versatile",
    name: "Llama 3.3 70B",
    provider: "Meta",
    apiProvider: "groq",
    contextWindow: 128000,
    maxOutput: 32768,
    inputCostPer1M: 0.59,
    outputCostPer1M: 0.79,
    speed: "ultrafast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["open-source", "fast"],
    releaseDate: "2024-12-06",
    category: "text",
  },
  {
    id: "llama-3.1-8b-instant",
    name: "Llama 3.1 8B",
    provider: "Meta",
    apiProvider: "groq",
    contextWindow: 128000,
    maxOutput: 8192,
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.08,
    speed: "ultrafast",
    accuracy: "medium",
    supportsStreaming: true,
    isLatest: false,
    tags: ["open-source", "ultra-cheap"],
    releaseDate: "2024-07-23",
    category: "text",
  },
  {
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    provider: "Meta",
    apiProvider: "groq",
    contextWindow: 128000,
    maxOutput: 8192,
    inputCostPer1M: 0.11,
    outputCostPer1M: 0.34,
    speed: "ultrafast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["open-source", "multimodal"],
    releaseDate: "2025-04-05",
    category: "text",
  },
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    provider: "Meta",
    apiProvider: "groq",
    contextWindow: 128000,
    maxOutput: 32768,
    inputCostPer1M: 0.22,
    outputCostPer1M: 0.88,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: true,
    tags: ["open-source", "flagship"],
    releaseDate: "2025-04-05",
    category: "text",
  },
  // ─── xAI Grok ──────────────────────────────────────────────
  {
    id: "grok-3",
    name: "Grok-3",
    provider: "xAI",
    apiProvider: "xai",
    contextWindow: 131072,
    maxOutput: 32768,
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: false,
    tags: ["reasoning", "real-time-web"],
    releaseDate: "2025-02-17",
    category: "text",
  },
  {
    id: "grok-3-mini",
    name: "Grok-3 Mini",
    provider: "xAI",
    apiProvider: "xai",
    contextWindow: 131072,
    maxOutput: 32768,
    inputCostPer1M: 0.3,
    outputCostPer1M: 0.5,
    speed: "ultrafast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["cheap", "fast"],
    releaseDate: "2025-02-17",
    category: "text",
  },
  {
    id: "grok-4",
    name: "Grok-4",
    provider: "xAI",
    apiProvider: "xai",
    contextWindow: 131072,
    maxOutput: 32768,
    inputCostPer1M: 5,
    outputCostPer1M: 20,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: true,
    tags: ["reasoning", "real-time-web"],
    releaseDate: "2025-06-01",
    category: "text",
  },
  {
    id: "grok-code",
    name: "Grok Code",
    provider: "xAI",
    apiProvider: "xai",
    contextWindow: 131072,
    maxOutput: 32768,
    inputCostPer1M: 2,
    outputCostPer1M: 8,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["code"],
    releaseDate: "2025-04-01",
    category: "text",
  },
  // ─── Mistral AI ────────────────────────────────────────────
  {
    id: "mistral-large-latest",
    name: "Mistral Large",
    provider: "Mistral AI",
    apiProvider: "mistral",
    contextWindow: 128000,
    maxOutput: 16384,
    inputCostPer1M: 2,
    outputCostPer1M: 6,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: true,
    tags: ["multilingual", "code"],
    releaseDate: "2024-11-01",
    category: "text",
  },
  {
    id: "mistral-small-latest",
    name: "Mistral Small",
    provider: "Mistral AI",
    apiProvider: "mistral",
    contextWindow: 32000,
    maxOutput: 8192,
    inputCostPer1M: 0.1,
    outputCostPer1M: 0.3,
    speed: "ultrafast",
    accuracy: "medium",
    supportsStreaming: true,
    isLatest: false,
    tags: ["cheap", "fast"],
    releaseDate: "2024-09-17",
    category: "text",
  },
  // ─── DeepSeek ──────────────────────────────────────────────
  {
    id: "deepseek-chat",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    apiProvider: "deepseek",
    contextWindow: 64000,
    maxOutput: 8192,
    inputCostPer1M: 0.27,
    outputCostPer1M: 1.1,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["code", "math", "cheap"],
    releaseDate: "2024-12-26",
    category: "text",
  },
  {
    id: "deepseek-reasoner",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    apiProvider: "deepseek",
    contextWindow: 64000,
    maxOutput: 32768,
    inputCostPer1M: 0.55,
    outputCostPer1M: 2.19,
    speed: "medium",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: true,
    tags: ["reasoning", "math", "code"],
    releaseDate: "2025-01-20",
    category: "text",
  },
  {
    id: "deepseek-v4",
    name: "DeepSeek V4",
    provider: "DeepSeek",
    apiProvider: "deepseek",
    contextWindow: 128000,
    maxOutput: 32768,
    inputCostPer1M: 0.27,
    outputCostPer1M: 1.1,
    speed: "fast",
    accuracy: "supreme",
    supportsStreaming: true,
    isLatest: true,
    tags: ["code", "math", "reasoning"],
    releaseDate: "2025-07-01",
    category: "text",
  },
  // ─── Zhipu GLM ─────────────────────────────────────────────
  {
    id: "glm-4-plus",
    name: "GLM-4 Plus",
    provider: "智谱AI",
    apiProvider: "zhipu",
    contextWindow: 128000,
    maxOutput: 4096,
    inputCostPer1M: 0.7,
    outputCostPer1M: 0.7,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: true,
    tags: ["chinese", "code", "vision"],
    releaseDate: "2024-09-01",
    category: "text",
  },
  {
    id: "glm-5",
    name: "GLM-5",
    provider: "智谱AI",
    apiProvider: "zhipu",
    contextWindow: 128000,
    maxOutput: 8192,
    inputCostPer1M: 0.7,
    outputCostPer1M: 0.7,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: true,
    tags: ["chinese", "code", "vision"],
    releaseDate: "2025-06-01",
    category: "text",
  },
  // ─── Moonshot Kimi ─────────────────────────────────────────
  {
    id: "moonshot-v1-128k",
    name: "Kimi moonshot-v1-128k",
    provider: "月之暗面",
    apiProvider: "moonshot",
    contextWindow: 128000,
    maxOutput: 4096,
    inputCostPer1M: 2,
    outputCostPer1M: 2,
    speed: "medium",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["chinese", "long-context"],
    releaseDate: "2024-04-01",
    category: "text",
  },
  {
    id: "moonshot-v1-8k",
    name: "Kimi moonshot-v1-8k",
    provider: "月之暗面",
    apiProvider: "moonshot",
    contextWindow: 8000,
    maxOutput: 4096,
    inputCostPer1M: 0.5,
    outputCostPer1M: 0.5,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: true,
    tags: ["chinese", "cheap"],
    releaseDate: "2024-04-01",
    category: "text",
  },
  {
    id: "kimi-k2",
    name: "Kimi K2",
    provider: "月之暗面",
    apiProvider: "moonshot",
    contextWindow: 128000,
    maxOutput: 8192,
    inputCostPer1M: 2,
    outputCostPer1M: 2,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: true,
    tags: ["chinese", "code"],
    releaseDate: "2025-09-01",
    category: "text",
  },
  // ─── Alibaba Qwen ──────────────────────────────────────────
  {
    id: "qwen-max",
    name: "Qwen Max",
    provider: "阿里巴巴",
    apiProvider: "qwen",
    contextWindow: 32768,
    maxOutput: 8192,
    inputCostPer1M: 0.4,
    outputCostPer1M: 1.2,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: true,
    tags: ["chinese", "code", "multilingual"],
    releaseDate: "2024-09-01",
    category: "text",
  },
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    provider: "阿里巴巴",
    apiProvider: "qwen",
    contextWindow: 128000,
    maxOutput: 16384,
    inputCostPer1M: 0.4,
    outputCostPer1M: 1.2,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: true,
    tags: ["chinese", "code", "reasoning"],
    releaseDate: "2025-06-01",
    category: "text",
  },
  {
    id: "qwen3-coder",
    name: "Qwen3 Coder",
    provider: "阿里巴巴",
    apiProvider: "qwen",
    contextWindow: 128000,
    maxOutput: 16384,
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.6,
    speed: "fast",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: false,
    tags: ["chinese", "code"],
    releaseDate: "2025-07-01",
    category: "text",
  },
  {
    id: "qwen-turbo",
    name: "Qwen Turbo",
    provider: "阿里巴巴",
    apiProvider: "qwen",
    contextWindow: 8192,
    maxOutput: 2048,
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.15,
    speed: "ultrafast",
    accuracy: "medium",
    supportsStreaming: true,
    isLatest: false,
    tags: ["chinese", "cheap", "fast"],
    releaseDate: "2024-01-01",
    category: "text",
  },
  // ─── Baidu ERNIE ───────────────────────────────────────────
  {
    id: "ernie-4.0-8k",
    name: "ERNIE 4.0",
    provider: "百度",
    apiProvider: "baidu",
    contextWindow: 8192,
    maxOutput: 2048,
    inputCostPer1M: 0.12,
    outputCostPer1M: 0.12,
    speed: "medium",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: true,
    tags: ["chinese", "search"],
    releaseDate: "2024-04-16",
    category: "text",
  },
  {
    id: "ernie-5.0",
    name: "ERNIE 5.0",
    provider: "百度",
    apiProvider: "baidu",
    contextWindow: 32768,
    maxOutput: 8192,
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.2,
    speed: "medium",
    accuracy: "high",
    supportsStreaming: true,
    isLatest: true,
    tags: ["chinese", "reasoning"],
    releaseDate: "2025-06-01",
    category: "text",
  },
  // ─── ByteDance Video ────────────────────────────────────────
  {
    id: "seedance-2.0",
    name: "Seedance 2.0",
    provider: "ByteDance",
    apiProvider: "aihubmix",
    contextWindow: 4096,
    maxOutput: 4096,
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    speed: "medium",
    accuracy: "supreme",
    supportsStreaming: false,
    isLatest: true,
    tags: ["video-gen"],
    releaseDate: "2025-06-01",
    category: "video",
  },
  // ─── Ollama (local, no API key required) ───────────────────
  {
    id: "llama3.2",
    name: "Llama 3.2 3B (本地)",
    provider: "Ollama",
    apiProvider: "ollama",
    contextWindow: 128000,
    maxOutput: 8192,
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    speed: "fast",
    accuracy: "medium",
    supportsStreaming: false,
    isLatest: true,
    tags: ["local", "free", "privacy", "open-source"],
    releaseDate: "2024-09-25",
    category: "text",
  },
  {
    id: "qwen2.5:7b",
    name: "Qwen 2.5 7B (本地)",
    provider: "Ollama",
    apiProvider: "ollama",
    contextWindow: 32768,
    maxOutput: 8192,
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    speed: "medium",
    accuracy: "medium",
    supportsStreaming: false,
    isLatest: false,
    tags: ["local", "free", "chinese", "open-source"],
    releaseDate: "2024-09-19",
    category: "text",
  },
  {
    id: "mistral",
    name: "Mistral 7B (本地)",
    provider: "Ollama",
    apiProvider: "ollama",
    contextWindow: 32768,
    maxOutput: 8192,
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    speed: "fast",
    accuracy: "medium",
    supportsStreaming: false,
    isLatest: false,
    tags: ["local", "free", "open-source"],
    releaseDate: "2023-09-27",
    category: "text",
  },
];

// Optimization mode → model scoring weights
export const MODE_WEIGHTS: Record<
  OptimizationMode,
  { token: number; speed: number; accuracy: number; aligned: number }
> = {
  token:    { token: 0.6, speed: 0.2, accuracy: 0.1, aligned: 0.1 },
  fast:     { token: 0.2, speed: 0.6, accuracy: 0.1, aligned: 0.1 },
  accurate: { token: 0.1, speed: 0.1, accuracy: 0.6, aligned: 0.2 },
  aligned:  { token: 0.1, speed: 0.1, accuracy: 0.3, aligned: 0.5 },
};

const SPEED_SCORE: Record<SpeedRating, number> = {
  ultrafast: 1,
  fast: 0.75,
  medium: 0.4,
  slow: 0.1,
};
const ACCURACY_SCORE: Record<AccuracyRating, number> = {
  supreme: 1,
  high: 0.75,
  medium: 0.45,
  low: 0.2,
};

/** Score a model for a given optimization mode (0–1) */
export function scoreModel(m: ModelInfo, mode: OptimizationMode): number {
  const w = MODE_WEIGHTS[mode];
  // Token score: lower cost → higher score (normalised to roughly 0-1)
  const avgCost = (m.inputCostPer1M + m.outputCostPer1M) / 2;
  const tokenScore = Math.max(0, 1 - avgCost / 80);
  const speedScore = SPEED_SCORE[m.speed];
  const accScore = ACCURACY_SCORE[m.accuracy];
  const alignedScore = (accScore + speedScore) / 2; // proxy
  return (
    w.token * tokenScore +
    w.speed * speedScore +
    w.accuracy * accScore +
    w.aligned * alignedScore
  );
}

/** Return top-N models for the given mode */
export function getTopModels(
  models: ModelInfo[],
  mode: OptimizationMode,
  n = 5
): ModelInfo[] {
  return [...models]
    .sort((a, b) => scoreModel(b, mode) - scoreModel(a, mode))
    .slice(0, n);
}

export const GENERATOR_AFFINITY: { prefix: string; recommended: string[] }[] = [
  { prefix: "gpt-5",     recommended: ["claude-sonnet-4-6", "gpt-4.1", "gemini-2.5-pro"] },
  { prefix: "gpt-4",     recommended: ["claude-sonnet-4-6", "gpt-4.1", "gemini-2.5-pro"] },
  { prefix: "o3",        recommended: ["claude-sonnet-4-6", "gpt-4.1"] },
  { prefix: "o4",        recommended: ["claude-sonnet-4-6", "gpt-4.1"] },
  { prefix: "claude-",   recommended: ["gpt-4.1", "gemini-2.5-pro", "claude-sonnet-4-6"] },
  { prefix: "gemini-",   recommended: ["claude-sonnet-4-6", "gpt-4.1", "gemini-2.5-pro"] },
  { prefix: "grok-",     recommended: ["claude-sonnet-4-6", "gpt-4.1"] },
  { prefix: "deepseek-", recommended: ["claude-sonnet-4-6", "gpt-4.1"] },
  { prefix: "llama-",    recommended: ["claude-sonnet-4-6", "gpt-4.1"] },
  { prefix: "glm-",      recommended: ["qwen-max", "claude-sonnet-4-6", "deepseek-chat"] },
  { prefix: "qwen-",     recommended: ["claude-sonnet-4-6", "deepseek-chat", "glm-4-plus"] },
  { prefix: "moonshot-", recommended: ["claude-sonnet-4-6", "qwen-max", "deepseek-chat"] },
  { prefix: "ernie-",    recommended: ["qwen-max", "claude-sonnet-4-6", "deepseek-chat"] },
];
